title: Brian Ryer
description: Tech. Writer | Information Mgmt.
theme: jekyll-theme-minimal
logo: "/assets/img/forum_image_square.png"

paginate: 2

tagline_morning: You look great!
tagline_evening: Enough with the taglines already!
tagline_special: Soup is good food.
tagline_super_special: Soup is really good food!

collections_dir: collections
collections:
  resume_sections:
  resume_skills:
  resume_positions:
