title: Brian Ryer
description: Writer, Developer
theme: jekyll-theme-minimal
logo: "/assets/img/forum_image_square.png"
tagline_morning: You look great!
tagline_evening: Enough with the taglines already!
tagline_special: Soup is good food.
