# my bs

title: Brian Ryer
description: Technical Writer
theme: jekyll-theme-minimal
logo: "/assets/img/forum_image_square.png"
plugins:
  - jekyll-feed

pages:
  output: true

collections_dir: collections
collections:
  resume_sections:
  resume_skills:
  resume_positions:
  posts:
      output          : true
  drafts:
  suits:

