title: Brian Ryer
description: Writer, Developer
theme: jekyll-theme-minimal
logo: "/assets/img/forum_image_square.png"
collections:
  taglines:
    morning: You look great!
    evening: Enough with the taglines already!
    special: Soup is good food.
