---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Posts
  create: all
- type: directory
  path: _resume_positions
  label: Resume positions
  create: all
  match: "**/*"
- type: directory
  path: _resume_skills
  label: Resume skills
  create: all
  match: "**/*"
- type: directory
  path: _resume_sections
  label: Resume sections
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
